[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/objets/1987-macintosh-se-1-1/"
to = "/objets/1983-commodore-executive-computer/"

[[redirects]]
from = "/projets/"
to = "/objets/"

[[redirects]]
from = "/objets/1987-commodore-executive-computer/"
to = "/objets/1983-commodore-executive-computer/"

[[redirects]]
from = "/objets/ordinateurs-personnel/"
to = "/objets/ordinateurs-personnels/"

[[redirects]]
from = "/objets/ordinateur-personnel/"
to = "/objets/ordinateurs-personnels/"

